export const types = Object.freeze({
  PROFILE_START_FETCHING: 'PROFILE_START_FETCHING',
  PROFILE_STOP_FETCHING: 'PROFILE_STOP_FETCHING',
  PROFILE_FILL: 'PROFILE_FILL',
  PROFILE_SET_FETCHING_ERROR: 'PROFILE_SET_FETCHING_ERROR',
  PROFILE_FETCH_ASYNC: 'PROFILE_FETCH_ASYNC'
});