export const types = Object.freeze({
  BREAKFAST_START_FETCHING: 'BREAKFAST_START_FETCHING',
  BREAKFAST_STOP_FETCHING: 'BREAKFAST_STOP_FETCHING',
  BREAKFAST_FILL: 'BREAKFAST_FILL',
  BREAKFAST_SET_FETCHING_ERROR: 'BREAKFAST_SET_FETCHING_ERROR',
  BREAKFAST_FETCH_ASYNC: 'BREAKFAST_FETCH_ASYNC'
});