export const types = Object.freeze({
  PROGRESS_BAR_START_FETCHING: 'PROGRESS_BAR_START_FETCHING',
  PROGRESS_BAR_STOP_FETCHING: 'PROGRESS_BAR_STOP_FETCHING',
  PROGRESS_BAR_FILL: 'PROGRESS_BAR_FILL',
  PROGRESS_BAR_SET_FETCHING_ERROR: 'PROGRESS_BAR_SET_FETCHING_ERROR',
  PROGRESS_BAR_FETCH_ASYNC: 'PROGRESS_BAR_FETCH_ASYNC'
});