export const types = Object.freeze({
  LOGGINING_START_FETCHING: 'LOGGINING_START_FETCHING',
  LOGGINING_STOP_FETCHING: 'LOGGINING_STOP_FETCHING',
  LOGGINING_FILL: 'LOGGINING_FILL',
  LOGGINING_SET_FETCHING_ERROR: 'LOGGINING_SET_FETCHING_ERROR',
  LOGGINING_FETCH_ASYNC: 'LOGGINING_FETCH_ASYNC'
});